export const ROUTES = {
    BASE: '',
    HOME: '',
    SUPER_ADMIN: {
        LOGIN: 'super-admin',
        WORKSPACES: 'workspaces',
        ADMINS: 'admins',
    },
    AUTH: {
        BASE: 'auth',
        LOGIN: 'login',
    },
    RESORTS: 'resort',
    PROPERTY: 'property',
    ASSET: {
        BASE: 'asset',
        UPSERT_AMENITIES: 'upsert-amenities/:id',
        UPSERT_IMAGES: 'upsert-images/:id',
    },
    CALENDAR: 'calendar',
    BLACKOUT_DATES: 'blackout-dates',
    CONTACT_US: 'contact-us',
    NEWSLETTER: 'newsletter',
    CANCELLED_ORDERS: 'cancelled-orders',
    TERMS_AND_CONDITIONS: 'terms-and-condition',
    PRIVACY_POLICY: 'privacy-policy',
    SUPPORT: 'support',
    PAGE_NOT_FOUND: '**',
    getFullRoute: (...slugs: string[]) => `/${slugs.join('/')}`,
};